### ISSUE TITLE
关于README.md/README_CN.md中的语言切换链接

### ISSUE THREAD

**Issue by ElemenTP** [TokiharaSay/Intel-NUC8i5BEH-Hackintos#1]
README.md中的中文版链接为<https://github.com/TokiharaSay/Intel-NUC8i5BEH-Hackintos/edit/main/README_CN.md>   
README_CN.md中的英文版链接为<https://github.com/TokiharaSay/Intel-NUC8i5BEH-Hackintos/edit/main/README.md>  
非contributor直接点击会提示需要folk。建议改为<https://github.com/TokiharaSay/Intel-NUC8i5BEH-Hackintos/blob/main/README_CN.md>和<https://github.com/TokiharaSay/Intel-NUC8i5BEH-Hackintos/blob/main/README.md>。

**Comment by TokiharaSay** [comment]
谢谢提醒
